paths:
  /user:
    get:
      summary: users list
      description: Return all users from the system
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
      tags:
        - user
    #put:
    #  #TODO
    post:
      summary: Add new user
      description: ''
      operationId: newUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserContent'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserContent'
      responses:
        '201':
          description: 'Create'
  /user/{id}:
    get:
      summary: informations on an user
      description: ''
      operationId: getUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the user
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/User'
        default:
          description: User's ID not exist
      tags:
        - user
      security:
        - OAuth2:
            - user
    #patch:
    #  #TODO
    delete:
      description: ''
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Delete complete
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/User'
        default:
          description: User's ID not exist
      tags:
        - user
  /user/me:
    get:
      summary: informations on current user
      operationId: getCurrentUser
      security:
        - OAuth2:
            - user
            - admin
      responses:
        default:
          description: ''
      tags:
        - user

components:
  schemas:
    User:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              minimum: 0
        - $ref: '#/components/schemas/UserContent'
      xml:
        name: User
    UserContent:
      type: object
      properties:
        #username:
        #  type: string
        #firstName:
        #  type: string
        #lastName:
        #  type: string
        img:
          #$ref: "#/components/schemas/Image"
          type: integer
          format: int64
          nullable: true
        email:
          type: string
        inscription:
          type: string
          format: date
      xml:
        name: UserData
