paths:
  /user:
    get:
      summary: users list
      description: Return all users from the system
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
      tags:
        - user
  /user/{id}:
    get:
      summary: informations on an user
      description: ''
      operationId: getUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the user
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/User'
        default:
          description: User's ID not exist
      tags:
        - user
      security:
        - OAuth2:
            - user
  /user/me:
    get:
      summary: informations on current user
      operationId: getCurrentUser
      security:
        - OAuth2:
            - user
            - admin
      responses:
        default:
          description: ''
      tags:
        - user

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        #username:
        #  type: string
        #firstName:
        #  type: string
        #lastName:
        #  type: string
        img:
          $ref: "#/components/schemas/Image"
        email:
          type: string
        inscription:
          type: string
          format: date
      xml:
        name: User
