paths:
  /article:
    get:
      summary: articles list
      description: Return all articles from the system
      operationId: getArticles
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Article'
      tags:
        - article
  /article/{id}:
    get:
      summary: informations on an article
      description: ''
      operationId: getArticle
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the article
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Article'
        default:
          description: Article's ID not exist
      tags:
        - article

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        name:
          type: string
        img:
          $ref: "#/components/schemas/Image"
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        description:
          type: string
        price:
          type: number
          format: float
        customerRating:
          type: number
          format: int32
