paths:
  /ad:
    get:
      summary: ads list
      description: Return all ads from the system
      operationId: getAds
      responses:
        '200':
          description: A list of ads
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: integer
                    format: int64
                  #  $ref: '#/components/schemas/Ad'
                  uniqueItems: true
      tags:
        - ads
    #put:
    #  #TODO
    post:
      summary: Add new ad
      description: ''
      operationId: newAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdContent'
          application/xml:
            schema:
              $ref: '#/components/schemas/AdContent'
      responses:
        '201':
          description: 'Create'
        '200':
          description: 'Created'
      tags:
        - ads
  /ad/{id}:
    get:
      summary: informations on an ad
      description: ''
      operationId: getAd
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the ad
          content:
            application/json:
                schema:
                  type: integer
        default:
          description: Ad's ID not exist
      tags:
        - ads
    #patch:
    #  #TODO
    delete:
      description: ''
      operationId: deleteAd
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Delete complete
          content:
            application/json:
                schema:
                  type: integer
        default:
          description: Ad's ID not exist
      tags:
        - ads

components:
  schemas:
    Ad:
      allOf:
        - $ref: '#/components/schemas/ObjId'
        - $ref: '#/components/schemas/AdContent'
      xml:
        name: Ad
    AdContent:
      type: object
      properties:
        description:
          type: string
          description: Short tip about the ad
        img:
          #$ref: "#/components/schemas/Image"
          type: integer
          format: int64
          nullable: true
      xml:
        name: AdData
