openapi: 3.0.0
servers: []
  #- url: 'http://api.ideal.com/'
  #  description: Ideal data API
  #  variables: {}
info:
  description: >-
    For this sample, you can use the api key `special-key` to test the
    authorization filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'https://esgi-ideal.github.io/terms/'
  contact:
    email: todo@reseau-ges.fr
    name: IDeal Shop Support
    url: 'https://esgi-ideal.github.io/support/'
  license:
    name: CC BY-SA 4.0
    url: 'https://creativecommons.org/licenses/by/4.0/'
tags:
  - name: article
    description: Everything about your articles
    externalDocs:
      description: Find out more
      url: 'http://todo/doc'
  - name: user
    description: Operations about user
  - name: partner
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our partners
      url: 'http://doc/todo'
  - name: ads
paths:
  /:
    get:
      summary: 'informations de base (statut, version ...)'
      description: ''
      operationId: apiInfos
      responses:
        200:
          description: 'OK'
          content:
            application/json:
                schema:
                  type: object
  /search:
    get:
      summary: search in articles
      description: ''
      parameters: []
      operationId: doSearch
      responses:
        default:
          description: Default response
      tags:
        - article
  /article:
    get:
      summary: articles list
      description: Return all articles from the system
      operationId: getArticles
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Article'
      tags:
        - article
  /article/{id}:
    get:
      summary: informations on an article
      description: ''
      operationId: getArticle
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the article
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Article'
        default:
          description: Article's ID not exist
      tags:
        - article
  /user:
    get:
      summary: users list
      description: Return all users from the system
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
      tags:
        - user
  /user/{id}:
    get:
      summary: informations on an user
      description: ''
      operationId: getUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the user
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/User'
        default:
          description: User's ID not exist
      tags:
        - user
      security:
        - OAuth2:
            - user
  /user/me:
    get:
      summary: informations on current user
      operationId: getCurrentUser
      security:
        - OAuth2:
            - user
            - admin
      responses:
        default:
          description: ''
      tags:
        - user
  /partner:
    get:
      summary: partners list
      description: Return all partners from the system
      operationId: getPartners
      responses:
        '200':
          description: A list of partner
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Partner'
      tags:
        - partner
  /partner/{id}:
    get:
      summary: informations on an partner
      description: ''
      operationId: getPartner
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the partner
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Partner'
        default:
          description: Partner's ID not exist
      tags:
        - partner
  /ad:
    get:
      summary: ads list
      description: Return all ads from the system
      operationId: getAds
      responses:
        '200':
          description: A list of ads
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: integer
                    format: int64
                  #  $ref: '#/components/schemas/Ad'
      tags:
        - ads
  /ad/{id}:
    get:
      summary: informations on an ad
      description: ''
      operationId: getAd
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the ad
          content:
            application/json:
                schema:
                  type: integer
        default:
          description: Ad's ID not exist
      tags:
        - ads
  /oauth2/token:
    post:
      summary: OAuth2 authnetication end-point
      operationId: oauth2Token
      #parameters: !!!
      requestBody:
        description: 'OAuth information for request'
        required: true
        content:
          #application/x-www-form-urlencoded
          '*/*':
            schema:
              type: object
              required:
                - grant_type
                - username
                - password
                - client_id
                - client_secret
                - scope
              properties:
                grant_type:
                    type: string
                    enum: [password]
                username:
                    type: string
                password:
                    type: string
                    format: password
                client_id:
                    type: string
                client_secret:
                    type: string
                    format: password
                scope:
                    type: array
                    #items:
                    #    type: string
      responses:
        '400':
            description: 'Access token error'
            content:
                application/json: {}
        default:
          description: ''
          content:
            application/json: {}
externalDocs:
  description: See API example
  url: 'https://esgi-ideal.github.io/'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        #username:
        #  type: string
        #firstName:
        #  type: string
        #lastName:
        #  type: string
        email:
          type: string
        password:
          type: string
          format: password
        inscription:
          type: string
          format: date
      xml:
        name: User
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        description:
          type: string
        price:
          type: number
          format: float
    Partner:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        img_url:
          type: string
        img_data:
          type: string
          format: byte
          description: ...
  responses:
    #'202':
    #    description: 'OK'
    #'201':
    #    description: 'Entity created'
    '204':
        description: 'Entity deleted'
    '304':
        description: 'Entity not modified'
    '400':
        description: 'Illegal input for operation'
    '406':
        description: 'Illegal input for operation'
    '404':
        description: 'Entity not found'
    '401':
        description: 'Authentication required for access this resource'
    '403':
        description: 'Privileges access refused'
    '409':
        description: 'Entity conflicts with operation'
  parameters:
    id:
        name: id
        in: path
        required: true
        schema:
            type: integer
            format: int64
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    OAuth2:
        type: oauth2
        flows:
            password:
                tokenUrl: "/oauth2/token"
                refreshUrl: "/oauth2/refresh"
                scopes:
                    user: Access to connected user
                    admin: Access to administrators
  links: {}
  callbacks: {}
security:
    - OAuth2: []
    #- ApiKey: []

