paths:
  /partner:
    get:
      summary: partners list
      description: Return all partners from the system
      operationId: getPartners
      responses:
        '200':
          description: A list of partner
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Partner'
                  uniqueItems: true
      tags:
        - partner
    #put:
    #  #TODO
    post:
      summary: Add new partner
      description: ''
      operationId: newPartner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartnerContent'
          application/xml:
            schema:
              $ref: '#/components/schemas/PartnerContent'
      responses:
        '201':
          description: 'Create'
      tags:
        - partner
  /partner/{id}:
    get:
      summary: informations on an partner
      description: ''
      operationId: getPartner
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the partner
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Partner'
        default:
          description: Partner's ID not exist
      tags:
        - partner
    #patch:
    #  #TODO
    delete:
      description: ''
      operationId: deletePartner
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Delete complete
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Partner'
        default:
          description: Partner's ID not exist
      tags:
        - partner

components:
  schemas:
    Partner:
      allOf:
        - $ref: '#/components/schemas/ObjId'
        - $ref: '#/components/schemas/PartnerContent'
      xml:
        name: Partner
    PartnerContent:
      type: object
      properties:
        name:
          type: string
        img:
          #$ref: "#/components/schemas/Image"
          type: integer
          format: int64
          nullable: true
        description:
          type: string
      xml:
        name: PartnerData
