paths:
  /partner:
    get:
      summary: partners list
      description: Return all partners from the system
      operationId: getPartners
      responses:
        '200':
          description: A list of partner
          content:
            application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Partner'
      tags:
        - partner
    #put:
    #  #TODO
    #post:
    #  #TODO
  /partner/{id}:
    get:
      summary: informations on an partner
      description: ''
      operationId: getPartner
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the partner
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Partner'
        default:
          description: Partner's ID not exist
      tags:
        - partner
    #patch:
    #  #TODO
    delete:
      description: ''
      operationId: deletePartner
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Delete complete
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Partner'
        default:
          description: Partner's ID not exist
      tags:
        - partner

components:
  schemas:
    Partner:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              minimum: 0
        - $ref: '#/components/schemas/PartnerContent'
    PartnerContent:
      type: object
      properties:
        name:
          type: string
        img:
          $ref: "#/components/schemas/Image"
        description:
          type: string
