paths:
  /ad:
    get:
      summary: ads list
      description: Return all ads from the system
      operationId: getAds
      responses:
        '200':
          description: A list of ads
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: integer
                    format: int64
                  #  $ref: '#/components/schemas/Ad'
      tags:
        - ads
  /ad/{id}:
    get:
      summary: informations on an ad
      description: ''
      operationId: getAd
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Datas on the ad
          content:
            application/json:
                schema:
                  type: integer
        default:
          description: Ad's ID not exist
      tags:
        - ads

components:
  schemas:
    Ad:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        description:
          type: string
          description: Short tip about the ad
        img:
          $ref: "#/components/schemas/Image"
