version: 2
references:
    common:
        workspace_root: &workspace_root
            ~/repo
        attach_workspace: &attach_workspace
            attach_workspace:
                at: *workspace_root
        restore_cache: &restore_cache
            restore_cache:
                keys:
                    - source-v1-{{ .Branch }}-{{ .Revision }}
                    - source-v1-{{ .Branch }}-
                    - source-v1-
                    #- m2-{{ checksum "pom.xml" }}
                    #- m2-
        save_cache: &save_cache
            save_cache:
                paths:
                    - ~/.m2
                key: source-v1-{{ .Branch }}-{{ .Revision }}

    env_jobs:
        default_config: &common_config
            working_directory: *workspace_root
        java_default_config: &java_default_config
            docker:
                - image: circleci/openjdk:8-jdk
            environment:
                MAVEN_OPTS: -Xmx3200m
            <<: *common_config
        release_default_config: &release_default_config
            docker:
                - image: cibuilds/github:0.10
            <<: *common_config

jobs:
  build:
    <<: *java_default_config
    steps:
      - checkout
      - *restore_cache
      - run: mvn dependency:go-offline
      - run: mvn clean package -DskipTests -Dmaven.test.skip=true
      - *save_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
      - run: |
            mkdir -p /tmp/artifact
            cp target/*.jar /tmp/artifact
      - store_artifacts:
          path: /tmp/artifact
          destination: artifacts/

  test:
    <<: *java_default_config
    steps:
      - *restore_cache
      - *attach_workspace
      - run: mvn test
      #- run: mvn integration-test
      - store_test_results:
          path: target/surefire-reports

  release:
    <<: *release_default_config
    steps:
      - *attach_workspace
      - run:
          name: "Publish Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Auto release from ${CIRCLE_BRANCH}" -replace -draft TAG /tmp/artifact/

  release-develop:
    <<: *release_default_config
    steps:
      - *attach_workspace
      - run:
          name: "Publish Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Auto release from ${CIRCLE_BRANCH}" -replace -prerelease -draft TAG /tmp/artifact/

workflows:
  version: 2
  complete-flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires: &flow-release-requires
            - test
          filters:
            branches:
              #ignore: /.*/
              only: master
            tags: &flow-release-filter
              only: /^[vV]?\d+(\.\d+)*$/
      - release-develop:
          requires:
            <<: *flow-release-requires
          filters:
            branches:
              #ignore: /.*/
              only: develop
            tags:
              <<: *flow-release-filter
