version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/builder-base:latest
    steps:
      - checkout
workflows:
  version: 2
  silent:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
