version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
            #- m2-{{ checksum "pom.xml" }}
            #- m2-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: source-v1-{{ .Branch }}-{{ .Revision }}

      - run: mvn package -DskipTests -Dmaven.test.skip=true
      #- run: mvn integration-test
      - store_test_results:
          path: target/surefire-reports
      - run: |
            mkdir -p /tmp/artifact
            cp target/*.jar /tmp/artifact
      - store_artifacts:
          path: /tmp/artifact
          destination: artifacts/
